services:
  team-mapper:
    build: .
    env_file:
      - path: .env.docker
        required: false
    volumes:
      - ./outputs:/app/outputs
      - ./schema:/app/schema:ro
    working_dir: /app
