#!/usr/bin/env python3
"""
Judge generated event/team candidates with an LLM.

The script writes local JSONL judgments only. It does not modify MySQL and does
not mark mappings as confirmed. SofaScore/manual verification is still required.
"""

import argparse
import json
import os
from pathlib import Path

from openai import OpenAI

import team_mapping_core as core


SCRIPT_DIR = Path(__file__).resolve().parent
PROVIDER_DEFAULTS = {
    "openai": {
        "api_key_env": "OPENAI_API_KEY",
        "base_url": None,
        "model": "gpt-5.5",
    },
    "deepseek": {
        "api_key_env": "DEEPSEEK_API_KEY",
        "base_url": "https://api.deepseek.com",
        "model": "deepseek-v4-pro",
    },
}


SYSTEM_PROMPT = """
You are a strict sports data entity-resolution judge.
Decide whether two source events are the same real-world sports match and
whether their home and away teams refer to the same teams.

Rules:
- Football and basketball must never be mixed.
- Event IDs are source-specific and do not prove equality.
- Strong evidence: same sport, close kickoff time, equivalent opponent pair,
  same final score, same competition/tournament if present.
- Names may be aliases, abbreviations, translations, or include suffixes like FC/SC/CF.
- Home/away may be reversed; detect that explicitly.
- If evidence is incomplete, lower the confidence instead of guessing.
- The result is only a candidate judgment. SofaScore/manual verification is
  required before confirmation.

Return JSON only with these keys:
same_event, event_confidence, home_team_same, home_team_confidence,
away_team_same, away_team_confidence, home_away_reversed,
requires_sofascore_verification, recommended_review_status, reason.
recommended_review_status must be one of:
needs_sofascore_verification, manual_review, reject.
"""


def parse_args():
    parser = argparse.ArgumentParser(description="Judge team/event candidates with an LLM.")
    parser.add_argument("--llm-env-file", default=".env.llm", help="Optional LLM env file. Default: .env.llm")
    parser.add_argument("--input", required=True, help="Candidate JSONL generated by generate_team_candidates.py")
    parser.add_argument("--output", help="Output JSONL. Default: <input>.judgments.jsonl")
    parser.add_argument(
        "--provider",
        choices=tuple(PROVIDER_DEFAULTS),
        default=os.environ.get("LLM_PROVIDER", "openai"),
        help="LLM provider. Default: env LLM_PROVIDER or openai.",
    )
    parser.add_argument("--model", help="LLM model name.")
    parser.add_argument("--base-url", default=os.environ.get("LLM_BASE_URL"), help="OpenAI-compatible base URL override.")
    parser.add_argument("--api-key-env", help="Environment variable that stores the API key.")
    parser.add_argument("--limit", type=int, help="Max candidates to judge.")
    parser.add_argument("--dry-run", action="store_true", help="Do not call LLM; write request payloads for inspection.")
    return parser.parse_args()


def resolve_path(path):
    candidate = Path(path).expanduser()
    if candidate.is_absolute() or candidate.exists():
        return candidate
    script_relative = SCRIPT_DIR / candidate
    if script_relative.exists():
        return script_relative
    return candidate


def read_jsonl(path, limit=None):
    rows = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            rows.append(json.loads(line))
            if limit and len(rows) >= limit:
                break
    return rows


def compact_event(event):
    return {
        "source": event["source"],
        "sport": event["sport"],
        "event_id": event["event_id"],
        "start_time": event["start_time"],
        "home_team": {
            "id": event["home_team_id"],
            "name": event["home_team_name"],
        },
        "away_team": {
            "id": event["away_team_id"],
            "name": event["away_team_name"],
        },
        "score": {
            "home": event["home_score"],
            "away": event["away_score"],
        },
        "competition": {
            "id": event["competition_id"],
            "name": event["competition_name"],
        },
    }


def build_payload(candidate):
    return {
        "task": "Judge if these two records describe the same real-world sports match and team identities.",
        "source_event": compact_event(candidate["source_event"]),
        "candidate_event": compact_event(candidate["candidate_event"]),
        "precomputed_signals": candidate["score_detail"],
        "sofascore_search_url": candidate["sofascore_search_url"],
    }


def judge_candidate(client, model, provider, candidate):
    payload = build_payload(candidate)
    params = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT.strip()},
            {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
        ],
        "response_format": {"type": "json_object"},
        "temperature": 0,
    }
    if provider == "deepseek":
        params["extra_body"] = {"thinking": {"type": "disabled"}}
    response = client.chat.completions.create(**params)
    text = response.choices[0].message.content
    if not text:
        raise RuntimeError("LLM returned empty content.")
    return json.loads(text)


def normalize_judgment(judgment):
    status = judgment.get("recommended_review_status")
    if status not in {"needs_sofascore_verification", "manual_review", "reject"}:
        status = "manual_review"
    judgment["recommended_review_status"] = status
    judgment["requires_sofascore_verification"] = True
    return judgment


def main():
    args = parse_args()
    llm_env_path = resolve_path(args.llm_env_file)
    if llm_env_path.exists():
        import db_connection_test as dbt

        dbt.load_env_file(llm_env_path)

    provider_defaults = PROVIDER_DEFAULTS[args.provider]
    provider_model_env = f"{args.provider.upper()}_MODEL"
    model = args.model or os.environ.get(provider_model_env) or provider_defaults["model"]
    base_url = args.base_url if args.base_url is not None else provider_defaults["base_url"]
    api_key_env = args.api_key_env or provider_defaults["api_key_env"]
    api_key = os.environ.get(api_key_env)

    input_path = resolve_path(args.input)
    candidates = read_jsonl(input_path, args.limit)
    output = Path(args.output).expanduser() if args.output else input_path.with_suffix(".judgments.jsonl")
    if not output.is_absolute():
        output = SCRIPT_DIR / output
    output.parent.mkdir(parents=True, exist_ok=True)

    if not args.dry_run and not api_key:
        raise SystemExit(f"Missing {api_key_env}. Run: export {api_key_env}='your_api_key'")

    client = None if args.dry_run else OpenAI(api_key=api_key, base_url=base_url)
    judged = 0
    with output.open("w", encoding="utf-8") as fh:
        for candidate in candidates:
            if args.dry_run:
                judgment = {
                    "dry_run_payload": build_payload(candidate),
                    "recommended_review_status": "needs_sofascore_verification",
                    "requires_sofascore_verification": True,
                }
            else:
                judgment = normalize_judgment(judge_candidate(client, model, args.provider, candidate))

            row = {
                "candidate_key": candidate["candidate_key"],
                "source_event": candidate["source_event"],
                "candidate_event": candidate["candidate_event"],
                "score_detail": candidate["score_detail"],
                "sofascore_search_url": candidate["sofascore_search_url"],
                "llm_provider": args.provider if not args.dry_run else None,
                "llm_model": model if not args.dry_run else None,
                "llm_judgment": judgment,
                "review_status": judgment["recommended_review_status"],
            }
            fh.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")
            judged += 1

    print(f"input_candidates={len(candidates)}")
    print(f"judged={judged}")
    print(f"output={output}")


if __name__ == "__main__":
    main()
